linux-yocto_4.4: drop bbappend from jethro branch
* this version of linux-yocto is not available in poky jethro branch,
leading to bitbake complaining for missing recipe

fixes:
ERROR: No recipes available for:
  meta-altera/recipes-kernel/linux/linux-yocto_4.4.bbappend